#cloud-config
runcmd:
 - |
   snap install microk8s --classic
   echo '-H tcp://0.0.0.0' >> /var/snap/microk8s/current/args/dockerd
   systemctl restart snap.microk8s.daemon-docker.service
   ln -s /var/snap/microk8s/current/docker.sock /var/run/docker.sock
   /snap/bin/microk8s.start
   /snap/bin/microk8s.status --wait-ready
   iptables -P FORWARD ACCEPT
   usermod -a -G microk8s ubuntu
   sudo apt update
   curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
   curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
   sudo apt-get update
   sudo apt-get install -y tailscale
   sudo tailscale up --authkey $TAILSCALE_TOKEN
   sudo cat > /lib/systemd/system/tailscale.service <<'EOF'
   [Unit]
   Description=Tailscale client
   After=tailscale.service

   [Service]
   LimitMEMLOCK=infinity
   User=root
   Group=root
   Type=simple
   ExecStart=doppler run --command 'sudo /usr/bin/tailscale up -authkey $TAILSCALE_AUTH_KEY'
   Restart=on-failure

   [Install]
   WantedBy=multi-user.target
   EOF
   systemctl daemon-reload
   systemctl enable tailscale.service
   systemctl start tailscale.service

write_files:
  - content: |
      #!/bin/sh
      iptables -P FORWARD ACCEPT
    path: /etc/rc.local
    permissions: '0755'